package com.wy.model;

public class CarInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.id
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.car_no
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    private String carNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.car_park
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    private Integer carPark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.user_name
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.phone
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.info
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.create_time
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.id
     *
     * @return the value of car_info.id
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.id
     *
     * @param id the value for car_info.id
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.car_no
     *
     * @return the value of car_info.car_no
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.car_no
     *
     * @param carNo the value for car_info.car_no
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo == null ? null : carNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.car_park
     *
     * @return the value of car_info.car_park
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public Integer getCarPark() {
        return carPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.car_park
     *
     * @param carPark the value for car_info.car_park
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public void setCarPark(Integer carPark) {
        this.carPark = carPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.user_name
     *
     * @return the value of car_info.user_name
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.user_name
     *
     * @param userName the value for car_info.user_name
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.phone
     *
     * @return the value of car_info.phone
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.phone
     *
     * @param phone the value for car_info.phone
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.info
     *
     * @return the value of car_info.info
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.info
     *
     * @param info the value for car_info.info
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.create_time
     *
     * @return the value of car_info.create_time
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.create_time
     *
     * @param createTime the value for car_info.create_time
     *
     * @mbggenerated Fri Nov 04 14:18:29 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}