package com.wy.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pass_word
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.cel_phone
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private String celPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wy_fee
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private Double wyFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.car_fee
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private Double carFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.car
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    private String car;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pass_word
     *
     * @return the value of user_info.pass_word
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pass_word
     *
     * @param passWord the value for user_info.pass_word
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name
     *
     * @return the value of user_info.real_name
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name
     *
     * @param realName the value for user_info.real_name
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.cel_phone
     *
     * @return the value of user_info.cel_phone
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public String getCelPhone() {
        return celPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.cel_phone
     *
     * @param celPhone the value for user_info.cel_phone
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setCelPhone(String celPhone) {
        this.celPhone = celPhone == null ? null : celPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wy_fee
     *
     * @return the value of user_info.wy_fee
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public Double getWyFee() {
        return wyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wy_fee
     *
     * @param wyFee the value for user_info.wy_fee
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setWyFee(Double wyFee) {
        this.wyFee = wyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.car_fee
     *
     * @return the value of user_info.car_fee
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public Double getCarFee() {
        return carFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.car_fee
     *
     * @param carFee the value for user_info.car_fee
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setCarFee(Double carFee) {
        this.carFee = carFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.car
     *
     * @return the value of user_info.car
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public String getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.car
     *
     * @param car the value for user_info.car
     *
     * @mbggenerated Fri Nov 11 20:13:33 CST 2022
     */
    public void setCar(String car) {
        this.car = car == null ? null : car.trim();
    }
}