package com.wy.model;

public class VisitInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.id
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.visit_user
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private String visitUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.address
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.visit_time
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private String visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.reason
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.car
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private String car;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.reply_content
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.is_deal
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private Integer isDeal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.user_id
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.create_time
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.id
     *
     * @return the value of visit_info.id
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.id
     *
     * @param id the value for visit_info.id
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.visit_user
     *
     * @return the value of visit_info.visit_user
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public String getVisitUser() {
        return visitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.visit_user
     *
     * @param visitUser the value for visit_info.visit_user
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setVisitUser(String visitUser) {
        this.visitUser = visitUser == null ? null : visitUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.address
     *
     * @return the value of visit_info.address
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.address
     *
     * @param address the value for visit_info.address
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.visit_time
     *
     * @return the value of visit_info.visit_time
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public String getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.visit_time
     *
     * @param visitTime the value for visit_info.visit_time
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setVisitTime(String visitTime) {
        this.visitTime = visitTime == null ? null : visitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.reason
     *
     * @return the value of visit_info.reason
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.reason
     *
     * @param reason the value for visit_info.reason
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.car
     *
     * @return the value of visit_info.car
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public String getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.car
     *
     * @param car the value for visit_info.car
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setCar(String car) {
        this.car = car == null ? null : car.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.reply_content
     *
     * @return the value of visit_info.reply_content
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.reply_content
     *
     * @param replyContent the value for visit_info.reply_content
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.is_deal
     *
     * @return the value of visit_info.is_deal
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public Integer getIsDeal() {
        return isDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.is_deal
     *
     * @param isDeal the value for visit_info.is_deal
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setIsDeal(Integer isDeal) {
        this.isDeal = isDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.user_id
     *
     * @return the value of visit_info.user_id
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.user_id
     *
     * @param userId the value for visit_info.user_id
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.create_time
     *
     * @return the value of visit_info.create_time
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.create_time
     *
     * @param createTime the value for visit_info.create_time
     *
     * @mbggenerated Mon Nov 07 21:21:40 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}